#!/run/current-system/sw/bin/bash

info() {
    CLASS=`xprop -id $(bspc query -N -n .focused -d .focused) | grep -E "^WM_CLASS" | grep -oE ', ".+"' | tr -d '," '`
    TITLE=`xtitle $(bspc query -N -n .focused -d .focused)`
    echo "{\"class\":\"$CLASS\", \"title\": \"$TITLE\"}"
}

info
bspc subscribe desktop node_focus | while read -r _ ; do
    info
done
