#!/run/current-system/sw/bin/bash

get_status() {
    STATUS=$(spotifycli --playbackstatus)
    if [[ $STATUS == *"▶"* ]]; then
        echo "playing"
    else
        echo "paused"
    fi
}

get_cover() {
    COVER=`spotifycli --arturl`
    echo $COVER
}

toggle() {
    STATUS=`get_status`
    echo "$STATUS"
    spotifycli --playpause &
    if [[ "$STATUS" == "playing" ]]; then
        eww update song_status=paused
    else
        eww update song_status=playing
    fi
}

if [[ "$1" == "--song" ]]; then
    spotifycli --song
elif [[ "$1" == "--artist" ]]; then
    spotifycli --artist
elif [[ "$1" == "--status" ]]; then
    get_status
elif [[ "$1" == "--time" ]]; then
    spotifycli --position | tr -d '()'
elif [[ "$1" == "--ctime" ]]; then
    spotifycli --position | tr -d '()' | awk -F'/' '{ print $1 }'
elif [[ "$1" == "--ttime" ]]; then
    spotifycli --postiion | tr -d '()' | awk -F'/' '{ print $2 }'
elif [[ "$1" == "--cover" ]]; then
    get_cover
elif [[ "$1" == "--toggle" ]]; then
    toggle
elif [[ "$1" == "--next" ]]; then
    spotifycli --next
elif [[ "$1" == "--prev" ]]; then
    spotifycli --prev
elif [[ "$1" == "--scroll" ]]; then
    if [[ "$2" == "up" ]]; then
        spotifycli --next
    elif [[ "$2" == "down" ]]; then
        spotifycli --prev
    fi
fi
