#!/run/current-system/sw/bin/bash

listen() {
    swaync-client -s | while read -r event; do
        echo "$event" | jq -Mc ".count"
    done
}

dnd() {
    swaync-client -d
    eww -c update notifications_dnd=$(swaync-client -D)
}

if [[ "$1" == "--toggle" ]]; then
    swaync-client -t -sw
elif [[ "$1" == "--listen" ]]; then
    listen
elif [[ "$1" == "--dnd" ]]; then
    swaync-client -d
elif [[ "$1" == "--get-dnd" ]]; then
    swaync-client -D
fi
