#!/run/current-system/sw/bin/bash

LOCK_FILE_CAL="$HOME/.cache/eww-calendar.lock"
LOCK_FILE_NOTIFICATIONS="$HOME/.cache/eww-notifications.lock"
LOCK_FILE_POWERMENU="$HOME/.cache/eww-powermenu.lock"
LOCK_FILE_TODO="$HOME/.cache/eww-todolist.lock"

calendar() {
    run() {
        eww open calendar
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_CAL" ]]; then
        eww close notification_tray power_menu todo_list
        touch "$LOCK_FILE_CAL"
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_POWERMENU
        rm $LOCK_FILE_TODO
        run && echo "ok good!"
    else
        eww close calendar
        rm "$LOCK_FILE_CAL" && echo "closed"
    fi
}

notifications() {
    run() {
        eww open notification_tray
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_NOTIFICATIONS" ]]; then
        eww close notification_tray power_menu todo_list
        touch "$LOCK_FILE_NOTIFICATIONS"
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_POWERMENU
        rm $LOCK_FILE_TODO
        run && echo "ok good!"
    else
        eww close notification_tray
        rm "$LOCK_FILE_NOTIFICATIONS" && echo "closed"
    fi
}

powermenu() {
    run() {
        eww open power_menu
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_POWERMENU" ]]; then
        eww close notification_tray power_menu todo_list
        touch "$LOCK_FILE_POWERMENU"
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_TODO
        run && echo "ok good!"
    else
        eww close power_menu
        rm "$LOCK_FILE_POWERMENU" && echo "closed"
    fi
}

todo() {
    run() {
        eww open todo_list
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_TODO" ]]; then
        eww close notification_tray power_menu todo_list
        touch "$LOCK_FILE_TODO"
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_POWERMENU
        run && echo "ok good!"
    else
        eww close todo_list
        rm "$LOCK_FILE_TODO" && echo "closed"
    fi
}

if [ "$1" = "--calendar" ]; then
    calendar
elif [ "$1" = "--notifications" ]; then
    notifications
elif [ "$1" = "--powermenu" ]; then
    powermenu
elif [[ "$1" = "--todo" ]]; then
    todo
fi
