#!/run/current-system/sw/bin/bash
LOCK_FILE_CAL="$HOME/.cache/eww-calendar.lock"
LOCK_FILE_SONG="$HOME/.cache/eww-music.lock"
LOCK_FILE_SETTINGS="$HOME/.cache/eww-system.lock"
LOCK_FILE_NOTIFICATIONS="$HOME/.cache/eww-notifications.lock"
LOCK_FILE_POWERMENU="$HOME/.cache/eww-powermenu.lock"

calendar() {
    run() {
        eww open calendar
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_CAL" ]]; then
        eww close music_win system_settings notification_tray power_menu
        touch "$LOCK_FILE_CAL"
        rm $LOCK_FILE_SONG
        rm $LOCK_FILE_SETTINGS
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_POWERMENU
        run && echo "ok good!"
    else
        eww close calendar
        rm "$LOCK_FILE_CAL" && echo "closed"
    fi
}

music() {
    run() {
        eww open music_win
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_SONG" ]]; then
        eww close calendar system_settings notification_tray power_menu
        touch "$LOCK_FILE_SONG"
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_SETTINGS
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_POWERMENU
        run && echo "ok good!"
    else
        eww close music
        rm "$LOCK_FILE_SONG" && echo "closed"
    fi
}

settings() {
    run() {
        eww open system_settings
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_SETTINGS" ]]; then
        eww close music_win calendar notification_tray power_menu
        touch "$LOCK_FILE_SETTINGS"
        rm $LOCK_FILE_SONG
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_POWERMENU
        run && echo "ok good!"
    else
        eww close system_settings
        rm "$LOCK_FILE_SETTINGS" && echo "closed"
    fi
}

notifications() {
    run() {
        eww open notification_tray
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_NOTIFICATIONS" ]]; then
        eww close music_win calendar settings power_menu
        touch "$LOCK_FILE_NOTIFICATIONS"
        rm $LOCK_FILE_SONG
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_SETTINGS
        rm $LOCK_FILE_POWERMENU
        run && echo "ok good!"
    else
        eww close notification_tray
        rm "$LOCK_FILE_NOTIFICATIONS" && echo "closed"
    fi
}

powermenu() {
    run() {
        eww open power_menu
    }

    # Open widgets
    if [[ ! -f "$LOCK_FILE_POWERMENU" ]]; then
        eww close music_win calendar settings
        touch "$LOCK_FILE_POWERMENU"
        rm $LOCK_FILE_NOTIFICATIONS
        rm $LOCK_FILE_SONG
        rm $LOCK_FILE_CAL
        rm $LOCK_FILE_SETTINGS
        run && echo "ok good!"
    else
        eww close power_menu
        rm "$LOCK_FILE_POWERMENU" && echo "closed"
    fi
}

if [ "$1" = "--calendar" ]; then
    calendar
elif [ "$1" = "--music" ]; then
    music
elif [ "$1" = "--settings" ]; then
    settings
elif [ "$1" = "--notifications" ]; then
    notifications
elif [ "$1" = "--powermenu" ]; then
    powermenu
fi
