#!/run/current-system/sw/bin/bash

launch() {
    eww open-many statusbar0 statusbar1 statusbar2
}

close() {
    eww close-all
}

ping() {
    eww ping
}

if [[ "$1" == "--launch" ]]; then
    launch
elif [[ "$1" == "--close" ]]; then
    close
elif [[ "$1" == "--ping" ]]; then
    ping
fi
