#!/run/current-system/sw/bin/bash

# Files and data
PREV_TOTAL=0
PREV_IDLE=0
cpuFile="/tmp/.cpu_usage"

# Get cpu usage
get_cpu() {
    if [[ -f "${cpuFile}" ]]; then
        fileCont=$(cat "${cpuFile}")
        PREV_TOTAL=$(echo "${fileCont}" | head -n 1)
        PREV_IDLE=$(echo "${fileCont}" | tail -n 1)
    fi

    CPU=(`cat /proc/stat | grep '^cpu '`)
    unset CPU[0]
    IDLE=${CPU[4]}

    TOTAL=0
    for VALUE in "${CPU[@]:0:4}"; do
        let "TOTAL=$TOTAL+$VALUE"
    done

    if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
        let "DIFF_IDLE=$IDLE-$PREV_IDLE"
        let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
        let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIF_IDLE)/$DIFF_TOTAL+5)/10"
        echo "${DIFF_USAGE}"
    else
        echo "?"
    fi

    # Remember the total and idle CPU times for the next check.
    echo "${TOTAL}" > "${cpuFile}"
    echo "${IDLE}" >> "${cpuFile}"
}

# Get used memory
get_mem() {
    printf "%.0f\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}')
}

# Get brightness
get_blight() {
    CARD=`ls /sys/class/backlight | head -n 1`

    if [[ "$CARD" == *"intel_"* ]]; then
        BNESS=`xbacklight -get`
        LIGHT=${BNESS%.*}
    else
        BNESS=`blight -d $CARD get brightness`
        PERC="$(($BNESS*100/255))"
        LIGHT=${PERC%.*}
    fi

    echo "$LIGHT"
}

# Get battery
get_battery() {
    BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
    cat /sys/class/power_supply/$BAT/capacity
}

# Execute accordingly
if [[ "$1" == "--cpu" ]]; then
    get_cpu
elif [[ "$1" == "--mem" ]]; then
    get_mem
elif [[ "$1" == "--blight" ]]; then
    get_blight
elif [[ "$1" == "--bat" ]]; then
    get_battery
fi

#vi: ft=bash
