#!/run/current-system/sw/bin/bash

check_alive() {
    MESSAGE=$(spotifycli --song)
    if [[ -z $MESSAGE ]]; then
        echo false
    else
        echo true
    fi
}

check_alive
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do
    check_alive
done
