#!/run/current-system/sw/bin/bash

memory() {
    free -m | grep "Mem" | awk '{ print $3/1000"/"$2/1000" GB"}'
}

memory_value() {
    free -g | grep "Mem" | awk -v OFMT="%.0f" '{ print $3/$2*100 }'
}

disk() {
    df -B 1G | grep "/$" | awk '{ print $3/1000"/"$2/1000" TB"}'
}

disk_value() {
    df -B 1G | grep "/$" | awk -v OFMT="%.0f" '{ print $3/$2*100 }'
}

if [[ "$1" == "--memory" ]]; then
    memory
elif [[ "$1" == "--memory-value" ]]; then
    memory_value
elif [[ "$1" == "--disk" ]]; then
    disk
elif [[ "$1" == "--disk-value" ]]; then
    disk_value
fi
