#!/run/current-system/sw/bin/bash

source ./scripts/visualizer_data

parse() {
    OUT=""
    for i in `echo $1 | sed 's/;/ /g'`; do
        OUT=$OUT${visualizer_map[$i]}
    done
    echo $OUT
}

cava -p ./scripts/config/cavaconf | while read -r line; do
    parse $line
done

